<a href="https://colab.research.google.com/github/ajaykumar080286/Numpy/blob/main/NumpyList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np
import pandas as pd

In [63]:
lista=range(100)
arr11=np.arange(100)

In [64]:
import sys

In [65]:
sys.getsizeof(87)*len(lista)

2800

In [66]:
arr11.itemsize*arr11.size

800

In [67]:
arr11.size

100

In [68]:
import time

In [69]:
x=range(100000)
y=range(100000,200000)

**for python**

In [70]:
st_time=time.time()
c=[(x,y) for x,y in zip(x,y)]

print(time.time()-st_time)

0.025998592376708984


**Numpy**

In [71]:
a=np.arange(100000)
b=np.arange(100000,200000)

In [72]:
st_time=time.time()
c1=a+b
print(time.time()-st_time)

0.0011065006256103516


In [73]:
arr12=np.arange(24)

In [74]:
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
arr12.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
arr12.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [77]:
arr1=np.array([1,2,3,4,5])

In [78]:
arr1

array([1, 2, 3, 4, 5])

In [79]:
arr1[3]

np.int64(4)

In [80]:
arr1[2:4]

array([3, 4])

In [81]:
arr1[-1]

np.int64(5)

**Slicing**

In [82]:
arr12=arr12.reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
arr12[2]

array([ 8,  9, 10, 11])

In [84]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [85]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [86]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [87]:
arr12[4:6,2:4]

array([[18, 19],
       [22, 23]])

***Iteration***

In [88]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [89]:
for i in arr12:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [90]:
for i in np.nditer(arr12):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


**Basic Operation**

In [92]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [98]:
arr1-arr2  #vercor sub/add

array([-3, -3, -3, -3, -3, -3])

In [97]:
arr1*arr2  #vector mulitplication

array([ 4, 10, 18, 28, 40, 54])

In [96]:
arr1*2  #scaler multiplcation

array([ 2,  4,  6,  8, 10, 12])

In [99]:
arr2

array([4, 5, 6, 7, 8, 9])

In [101]:
arr2>4

array([False,  True,  True,  True,  True,  True])

**Dot Product**

In [108]:
arr3=np.arange(6)
arr3

array([0, 1, 2, 3, 4, 5])

In [109]:
arr3=np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [110]:
arr4=np.arange(6).reshape(3,2)
arr4

array([[0, 1],
       [2, 3],
       [4, 5]])

In [111]:
arr3.shape

(2, 3)

In [112]:
arr4.shape

(3, 2)

In [114]:
arr3.dot(arr4)

array([[10, 13],
       [28, 40]])

In [115]:
arr4

array([[0, 1],
       [2, 3],
       [4, 5]])

In [116]:
arr4.max()

np.int64(5)

In [121]:
arr4.min(axis=1)  #row wise nin value

array([0, 2, 4])

In [118]:
arr4.mean()

np.float64(2.5)

In [122]:
arr4.mean(axis=0)#column wise

array([2., 3.])

In [124]:
arr4.sum(axis=0)

array([6, 9])

In [126]:
arr4.std()

np.float64(1.707825127659933)

In [127]:
arr4.std(axis=1)

array([0.5, 0.5, 0.5])

In [128]:
np.median(arr4)

np.float64(2.5)

In [129]:
np.sin(arr4)

array([[ 0.        ,  0.84147098],
       [ 0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427]])

In [130]:
np.exp(arr4)

array([[  1.        ,   2.71828183],
       [  7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 ]])