<a href="https://colab.research.google.com/github/ajaykumar080286/Numpy/blob/main/NumpyList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

In [8]:
lista=range(100)
arr11=np.arange(100)

In [9]:
import sys

In [11]:
sys.getsizeof(87)*len(lista)

2800

In [12]:
arr11.itemsize*arr11.size

800

In [13]:
arr11.size

100

In [15]:
import time

In [25]:
x=range(100000)
y=range(100000,200000)

**for python**

In [26]:
st_time=time.time()
c=[(x,y) for x,y in zip(x,y)]

print(time.time()-st_time)

0.039353370666503906


**Numpy**

In [28]:
a=np.arange(100000)
b=np.arange(100000,200000)

In [29]:
st_time=time.time()
c1=a+b
print(time.time()-st_time)

0.0014996528625488281


In [30]:
arr12=np.arange(24)

In [31]:
arr12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
arr12.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
arr12.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [34]:
arr1=np.array([1,2,3,4,5])

In [35]:
arr1

array([1, 2, 3, 4, 5])

In [36]:
arr1[3]

np.int64(4)

In [37]:
arr1[2:4]

array([3, 4])

In [38]:
arr1[-1]

np.int64(5)

**Slicing**

In [46]:
arr12=arr12.reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
arr12[2]

array([ 8,  9, 10, 11])

In [48]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [52]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [54]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [57]:
arr12[4:6,2:4]

array([[18, 19],
       [22, 23]])

***Iteration***

In [60]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
for i in arr12:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [61]:
for i in np.nditer(arr12):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
