<a href="https://colab.research.google.com/github/ajaykumar080286/Numpy/blob/main/NumpyEX1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#creating numpy n-d array

In [ ]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [ ]:
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
arr3=np.array([[1,2],[2,3.2]])

In [ ]:
arr3

array([[1. , 2. ],
       [2. , 3.2]])

In [ ]:
arr4=np.zeros((2,3))

In [ ]:
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr5=np.ones((3,3))

In [ ]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr7=np.arange(5,16)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr8=np.arange(5,16,2)
arr8

array([ 5,  7,  9, 11, 13, 15])

In [ ]:
arr9=np.linspace(10,20,10)  # equal distance
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
arr10=arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

**We learned**

In [ ]:
np.zeros((2,3))
np.ones((2,3))
np.arange(10)
np.identity(4)
np.linspace(2,4,2)
a8.copy()

array([0. , 4.5, 9. ])

***Numpy Part 4 - Some Important Attributes***

In [ ]:
arr1.shape

(5,)

In [ ]:
arr1.ndim

1

In [ ]:
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
arr2.shape

(2, 5)

In [ ]:
arr2.ndim

2

In [ ]:
arr11=np.array([[[2,3],[2,3]],
[[3,4],[5,6]]])

In [ ]:
arr11

array([[[2, 3],
        [2, 3]],

       [[3, 4],
        [5, 6]]])

In [ ]:
arr11.shape

(2, 2, 2)

In [ ]:
arr11.ndim

3

In [ ]:
arr1.ndim

1

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1.size

5

In [ ]:
arr9.size

10

In [ ]:
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
arr9.itemsize

8

In [ ]:
arr8.dtype

dtype('int64')

In [ ]:
arr9.dtype

dtype('float64')

In [ ]:
arr8=arr8.astype('float')

In [ ]:
arr8.dtype

dtype('float64')

In [ ]:
arr9.astype('int')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])