<a href="https://colab.research.google.com/github/ajaykumar080286/Numpy/blob/main/Reshape_np_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
arr4=np.arange(6).reshape(3,2)
arr4

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
arr4.ndim

2

In [8]:
arr4.ravel()  # higer dim to 1d

array([0, 1, 2, 3, 4, 5])

In [10]:
arr4.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

In [11]:
arr4

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
arr5=np.arange(12,18).reshape(2,3)

In [13]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [15]:
arr3=np.arange(6).reshape(2,3)

In [16]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
arr3.shape

(2, 3)

In [18]:
arr5.shape

(2, 3)

In [19]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [21]:
np.vstack((arr3,arr5))  #vertical stach

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [22]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [24]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

**Fancy indexing in Numpy**

In [25]:
arr8=np.arange(24).reshape(6,4)

In [26]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
#i need first row , 3th row & 5ht row ,not possible by slicing & indexing

In [28]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

***Numpy Part 10 - Indexing with Boolean Arrays***